server:
    port: 8080

spring:
    servlet:
        multipart:
            max-file-size: 2048000KB
            max-request-size: 2048000KB
    jpa:
        database: MYSQl
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://localhost:3306/project_scope?createIfNotExists=true&useSSL=false&useTimezone=true&serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        tomcat:
            connection-properties: useUnicode=true;characterEncoding=utf-8
        hikari:
            data-source-properties.useUnicode: true
            data-source-properties.characterEncoding: UTF-8
    thymeleaf:
        cache: false
    mail:
        host: smtp.gmail.com
        port: 587
        username:
        password:

        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true


#images:
#    user: C:\\Users\\Hov\\Desktop\\GIT JAVA\\WorkPlace\\ot\\src\\main\\resources\\static\\images\\resource\\
#video:
#    user: C:\\Users\\Hov\\Desktop\\GIT JAVA\\WorkPlace\\ot\\src\\main\\resources\\static\\images\\resource\\
baseUrl: http://localhost:8080/
